config/routes.rb
GalleryRails::Application.routes.draw do

  resources :photos, :only => [] do
    match "get_next/(:last_id)" => "photos#get_photos", :on => :collection, :as => "get_next"
    get "crop" => "photos#crop", :as => "crop", :on => :member
  end

  resources :albums do
    resources :photos  do
      match 'get/:which' => "albums#get_photo", :on => :member, :as => "get"
      post 'get_photos/(:last_id)' => "photos#get_photos" , :on => :collection, :as => "get"
    end
  end

  devise_for :users ,:path => "" ,:path_names => {:sign_in => 'login', :sign_up => "register",:sign_out => 'logout'},
             :controllers => { :confirmations => "users/confirmations", :omniauth_callbacks => "users/omniauth_callbacks"} do
    get '/login' => 'devise/sessions#new'
    post '/login' => 'devise/sessions#create'
    get '/logout' => 'devise/sessions#destroy'

    get '/register' => 'devise/registrations#new'
    post '/register' => 'devise/registrations#create'
  end

  get '/' => "home#root_page"
  root :to => "home#root_page"

end

app/models/album.rb
class Album
  include Mongoid::Document
  include Mongoid::Timestamps
  field :name

 # embedded_in :user
  belongs_to :user
  embeds_many :photos
  attr_accessible :name

  validates :name, :presence => true, :uniqueness => true, :length => {:in => 2..30}

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums = Album.all.sort{|b,a| a.photos.count <=> b.photos.count}
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @albums }
    end
  end

  def show
    @album = Album.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @album }
    end
  end

  def new
    @album = Album.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @album }
    end
  end

  def edit
    @album = Album.find(params[:id])
    @photos = @album.photos.asc(:id).take(15)

  end

  def create
    @album = Album.new(params[:album])
    @album.user = current_user
    respond_to do |format|
      if @album.save
        format.html { redirect_to albums_url, notice: 'Album was successfully created.' }
        format.json { render json: @album, status: :created, location: @album }
      else
        format.html { render action: "new" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @album = Album.find(params[:id])

    respond_to do |format|
      if @album.update_attributes(params[:album])
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy

    respond_to do |format|
      format.html { redirect_to albums_url }
      format.json { head :no_content }
    end
  end

  def get_photo
    @album = Album.find(params[:album_id])
    @photo = @album.photos.find(params[:id])
    @which = params[:which]
    photos = @album.photos.asc(:id)
    count_all = photos.count
    @prev = false
    @next = false

    if @which == "random"
      first_photo = photos.first
      last_photo = photos.last
      photos = photos.ne(id: @photo.id)
      res_photo = photos.sample
      @prev = true if first_photo.id != res_photo.id
      @next = true if last_photo.id != res_photo.id
    else
      if @which == "prev"
        photos = photos.lt(id: @photo.id).desc(:id)
        @prev = true if  photos.count > 1
        @next = true
      elsif @which == "next"
        photos = photos.gt(id: @photo.id)
        @prev = true
        @next = true if  photos.count > 1
      elsif @which == "first"
        @prev = false
        @next = true if count_all > 0
      elsif @which == "last"
        photos = photos.desc(:id)
        @prev = true if count_all > 0
        @next = false
      end
      res_photo = photos.first
    end

    respond_to do |format|
      format.json { render :json => {
          which: @which,
          prev: @prev,
          next: @next,
          :photo => {
              src: !res_photo.nil? ? res_photo.image(:medium) : "",
              id: !res_photo.nil? ? res_photo.id : "nil",
              description: !res_photo.nil? ? !res_photo.description.nil? ? res_photo.description : "" : ""
          }
        }
      }
    end
  end

end

app/views/albums/_form.html.erb
<%= simple_form_for(@album) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing album</h1>
<div class="help-links">
  <%= link_to(raw('<i class="icon-backward"></i> Show all'), albums_path) %>
  <%= link_to(raw('<i class="icon-eye-open"></i> Show'), @album) %>
</div>

<%= render 'form' %>

<h2>New photo</h2>
<%= render :partial => "photos/form", :locals => {album: @album, photo: @album.photos.new }  %>

  <b>Photos: </b>
  <div id="photos-container">
    <%= render :partial => "photos/photo", :collection => @photos %>
  </div>
<% if !@photos.empty? %>
    <%=  render :partial => "application/shared/more", :locals => {:path => get_album_photos_path(@album,{last_id: @photos.last.id, format: :json} ), :load_to => "#photos-container"}   %>
<% end %>

app/views/albums/index.html.erb
<h1>Listing albums</h1>
<div class="help-links"><%= link_to 'New Album', new_album_path, class: "btn" %></div>
<% @albums.each do |album| %>
    <div class="folder-icon-container">
        <%= link_to album , :class => "folder-icon" do %>
                <span class="name"><%= album.name %> (<%= album.photos.count %>)</span>
        <% end %>
        <%= image_tag(album.photos.first.image(:small), :class => "first-photo") if !album.photos.empty? %>
        <span class="links">
          <%= link_to(raw('<i class=" icon-eye-open"></i> Show'), album) %>
          <%= link_to(raw('<i class="icon-pencil"></i> Edit'), edit_album_path(album)) %>
          <%= link_to(raw('<i class="icon-trash"></i> Delete'), album, method: :delete, data: { confirm: 'Are you sure?' } )%>
        </span>
    </div>
<% end %>

app/views/albums/new.html.erb
<h1>New album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<%  if !@album.photos.empty? %>
    <% photo = @album.photos.first %>
    <div class="gallery-container">
      <div class="image">
         <%= image_tag(photo.image(:medium)) %>
      <div class="prev nav disabled" style="display: none;"><</div>
      <div class="next nav <%= 'disabled' if @album.photos.count < 2 %>" style="display: none;"> > </div>
        <div class="description"><%= photo.description %></div>
      </div>
      <div class="buttons">
        <div class="btn-group">
          <%= link_to raw('<i class="icon-backward"></i> first'), get_album_photo_path(@album, photo, :which => "first",:format => :json), :class => "btn navigation prev disabled" %>
          <%= link_to raw('<i class="icon-chevron-left"></i> prev'), get_album_photo_path(@album, photo, :which => "prev",:format => :json), :class => "btn navigation prev exactly-prev disabled" %>
          <%= link_to raw('<i class="icon-random"></i> random'), get_album_photo_path(@album, photo, :which => "random",:format => :json), :class => "btn navigation random #{'disabled' if @album.photos.count < 2}" %>
          <%= link_to raw('<i class="icon-chevron-right"></i> next'), get_album_photo_path(@album, photo, :which => "next",:format => :json), :class => "btn navigation next exactly-next #{'disabled' if @album.photos.count < 2}" %>
          <%= link_to raw('<i class="icon-forward"></i> last'), get_album_photo_path(@album, photo, :which => "last",:format => :json), :class => "btn navigation next #{'disabled' if @album.photos.count < 2}" %>
        </div>
      </div>
    </div>
<% end %>