config/routes.rb
GalleryRails::Application.routes.draw do

  resources :photos, :only => [] do
    match "get_next/(:last_id)" => "photos#get_photos", :on => :collection, :as => "get_next"
    get "crop" => "photos#crop", :as => "crop", :on => :member
  end

  resources :albums do
    resources :photos  do
      match 'get/:which' => "albums#get_photo", :on => :member, :as => "get"
      post 'get_photos/(:last_id)' => "photos#get_photos" , :on => :collection, :as => "get"
    end
  end

  devise_for :users ,:path => "" ,:path_names => {:sign_in => 'login', :sign_up => "register",:sign_out => 'logout'},
             :controllers => { :confirmations => "users/confirmations", :omniauth_callbacks => "users/omniauth_callbacks"} do
    get '/login' => 'devise/sessions#new'
    post '/login' => 'devise/sessions#create'
    get '/logout' => 'devise/sessions#destroy'

    get '/register' => 'devise/registrations#new'
    post '/register' => 'devise/registrations#create'
  end

  get '/' => "home#root_page"
  root :to => "home#root_page"

end

app/models/photo.rb
class Photo
  include Mongoid::Document
  include Mongoid::Paperclip
  include Mongoid::Timestamps
  embedded_in :album, :inverse_of => :photos
  field :description
  field :name

  attr_accessible :description, :name, :image_content_type, :image_file_name, :image_file_size, :image_updated_at, :album_id, :image,
                  :crop_x, :crop_y, :crop_w, :crop_h
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  after_update :reprocess_image, :if => :cropping?

  has_mongoid_attached_file :image, :styles => {
      :thumb  => "32x32",
      :small => "100x100",
      :medium => "600x500"
  },
  :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
  :url => "/system/:attachment/:id/:style/:filename",
  :processors => [:cropper]

  validates :image, :presence => true

  def cropping?
    !crop_x.blank? && !crop_y.blank? && !crop_w.blank? && !crop_h.blank?
  end

  def image_geometry(style = :original)
    @geometry ||= {}
    @geometry[style] ||= Paperclip::Geometry.from_file(image.path(style))
  end

  validates_attachment_presence :image
  validates_attachment_size :image, :less_than => 5.megabytes
  validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/png']

  private
  def reprocess_image
    image.reprocess!
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_filter :set_per_page

  def index
    @album = Album.find params[:album_id]
    @photos = @album.photos.asc(:id).take(@per_page)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photos }
    end
  end

  def crop
    @album = Album.find params[:album_id]
    @photo = @album.photos.find(params[:id])
  end

  def get_photos
    last_id = params[:last_id]
    @album = Album.find params[:album_id]

    @photos = @album.photos
    @photos = @photos.asc(:id)
    @photos = @photos.gt(id: last_id) if last_id and last_id != 'end'

    if @photos.empty? || params[:last_id] == 'end'
      new_last_id = "end"
    else
      new_last_id = @photos.last.id
    end

    @next_url = new_last_id == "end" ? "end" : get_album_photos_path(@album, {last_id: @photos.last.id, format: :json})

    respond_to do |format|
      format.json { render :json => {:url => @next_url,
                                     :html => render_to_string(:partial => "photos/photo", :collection => @photos)},
                           :layout => false }
    end
  end

  def new
    @album = Album.find params[:album_id]
    @photo = @album.photos.new
  end

  def show
    @album = Album.find params[:album_id]
    @photo = @album.photos.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photo }
    end
  end


  def edit
    @album = Album.find params[:album_id]
    @photo = @album.photos.find(params[:id])
  end

  def create
    @album = Album.find params[:album_id]
    @photo = @album.photos.create params[:photo]

    if @photo.save
      if params[:photo][:image].blank?
        flash[:notice] = 'Photo was successfully created.'
        redirect_to @album
      else
        render :action => "crop"
      end
    else
      render action: "new"
    end
  end

  def update
    @album = Album.find params[:album_id]
    @photo = @album.photos.find(params[:id])

    if @photo.update_attributes(params[:photo])
      if params[:photo][:image].blank?
        flash[:notice] = 'Photo was successfully updated.'
        redirect_to [@album, @photo]
      else
        render :action => "crop"
      end
    else
      render :action => 'edit'
    end
  end

  def destroy
    @album = Album.find params[:album_id]
    @photo = @album.photos.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to album_photos_url @album }
      format.json { head :no_content }
    end
  end

  private

  def set_per_page
    @per_page = 15
  end
end

app/views/photos/_form.html.erb
<%= simple_form_for([album, photo], :html => { :class => 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description, :input_html => {rows: 5, :class=> 'span5'}  %>
    <%= f.input :image, :as => :file %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/photos/_photo.erb
<% show = false if show.nil? %>
<div class="photo-preview" style="clear: both; margin-bottom: 10px; overflow: auto;">
  <div class="span2"><%= image_tag photo.image(:small) %></div>
  <div class="span4">
    <div style="font-weight: bold;"><%= photo.name %></div>
    <div style="font-style: italic;"><%= photo.description if !photo.description.nil? %></div>
    <div class="links">
      <%= link_to(raw('<i class=" icon-eye-open"></i> Show'), [photo.album, photo]) if !show %>
      <%= link_to(raw('<i class="icon-pencil"></i> Edit'), edit_album_photo_path(photo.album, photo)) %>
      <%= link_to(raw('<i class="icon-trash"></i> Delete'), [photo.album, photo], method: :delete, data: { confirm: 'Are you sure?' } )%>
    </div>
  </div>
  <div class="6"><%= image_tag photo.image(:medium) if show %></div>
</div>

app/views/photos/crop.html.erb
<h2>Crop photo</h2>
<script type="text/javascript" charset="utf-8">
$(function() {
  $('#cropbox').Jcrop({
    onChange: update_crop,
    onSelect: update_crop,
    setSelect: [0, 0, 500, 600],
    aspectRatio: 6/5
  });
});

function update_crop(coords) {
	var rx = 240/coords.w;
	var ry = 200/coords.h;

	$('#preview').css({
		width: Math.round(rx * <%= @photo.image_geometry(:medium).width %>) + 'px',
		height: Math.round(ry * <%= @photo.image_geometry(:medium).height %>) + 'px',
		marginLeft: '-' + Math.round(rx * coords.x) + 'px',
		marginTop: '-' + Math.round(ry * coords.y) + 'px',
        maxWidth: 'none'
	});
  var ratio = <%= @photo.image_geometry(:original).width %> / <%= @photo.image_geometry(:medium).width %>;

  $("#crop_x").val(Math.round(coords.x * ratio));
  $("#crop_y").val(Math.round(coords.y * ratio));
  $("#crop_w").val(Math.round(coords.w * ratio));
  $("#crop_h").val(Math.round(coords.h * ratio));
}
</script>


<div class="center-inner" style="margin-top: 15px;">
    <%= image_tag @photo.image.url(:medium), :id => "cropbox" %>
</div>

<div style="text-align: center; margin: 15px auto">
<h3>Preview</h3>
<div style="width:240px; height:200px; overflow:hidden;border: 5px solid #EE583D; display: inline-block; ">
  <%= image_tag @photo.image.url(:medium), :id => "preview" %>
</div>
<br><br>
<br>

<%= form_for @photo, :url => album_photo_path(@album, @photo) do |f| %>
  <% for attribute in [:crop_x, :crop_y, :crop_w, :crop_h] %>
    <%= f.hidden_field attribute, :id => attribute %>
  <% end %>
  <p><%= f.submit "Crop" %></p>
<% end %>
</div>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<div class="help-links">
  <%= link_to(raw('<i class="icon-backward"></i> Show all'), album_photos_path([@photo.album])) %>
  <%= link_to(raw('<i class="icon-eye-open"></i> Show'),  [@photo.album, @photo]) %>
</div>

<%= render :partial => "photos/form", locals: {photo: @photo, album: @album} %>

app/views/photos/index.html.erb
<h1>Listing photos</h1>
<div class="help-links"><%= link_to 'New Photo', new_album_photo_path(@album), :class => "btn" %></div>

<div id="photos-container">
  <%= render :partial => "photos/photo", :collection => @photos %>
</div>

<% if !@photos.empty? %>
  <%=  render :partial => "application/shared/more", :locals => {:path => get_album_photos_path(@album,{last_id: @photos.last.id, format: :json} ), :load_to => "#photos-container"}   %>
<% end %>

app/views/photos/new.html.erb
<h1>New photo to album <%= @album.name%></h1>

<div class="help-links">
  <%= link_to(raw('<i class="icon-backward"></i> Show all'), album_photos_path(@album)) %>
</div>

<%= render :partial => "photos/form", locals: {photo: @photo, album: @album} %>

app/views/photos/show.html.erb
<div class="help-links">
  <%= link_to(raw('<i class="icon-backward"></i> Show all'), album_photos_path([@photo.album])) %>
  <%= link_to(raw('<i class="icon-pencil"></i> Edit'), edit_album_photo_path([@photo.album, @photo])) %>
</div>

<%= render :partial => "photos/photo", locals: {show: true, photo: @photo} %>